#!/usr/bin/env python3
"""Build YURI1 Music's GitHub Pages track URLs, SEO pages, and sitemap.

Usage:
    python tools/build_music_pages.py
    python tools/build_music_pages.py --check

Source of truth: w-music/w-tracklog.json. The optional "url-title" overrides
only the URL's final path segment. Media file identity stays ID + Img.
"""
import argparse
import html
import json
import re
import sys
import unicodedata
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
SITE = 'https://music.yuri1.com/'
WWW = 'https://www.yuri1.com/'
TITLE_SUFFIX = 'YURI NO1 Music – Girls Love ♡ AI Music from Novels'
GENERATED_MARKER = '<!-- generated by tools/build_music_pages.py; edit w-music/w-tracklog.json instead -->'


def title_from_title(value):
    """Match config/music.js slugify exactly, including Unicode normalization."""
    value = unicodedata.normalize('NFKD', str(value or 'track').strip().lower())
    value = re.sub(r'[\u0300-\u036f]', '', value)
    value = re.sub(r'[^a-z0-9\u3040-\u30ff\u3400-\u9fff]+', '-', value)
    return value.strip('-') or 'track'


def url_title(track):
    custom = str(track.get('url-title') or '').strip().lower()
    if custom:
        if not re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*', custom):
            raise ValueError(f"{track.get('TITLE')!r}: invalid url-title {custom!r}; use a-z, 0-9, hyphens")
        return custom
    return title_from_title(track.get('TITLE'))


def music_id(track):
    source_id = str(track.get('ID') or '').strip()
    m = re.match(r'^(\d{8}-\d{2})', source_id)
    return 'm-p' + m[1] if m else 'm-' + source_id.lower().replace('_', '-')


def relative_dir(track):
    return Path('m') / music_id(track) / url_title(track)


def canonical(track):
    return SITE + relative_dir(track).as_posix() + '/'


def media(track, typ):
    suffix = {'image': '.jpg', 'audio': '.mp3', 'lyrics': '.txt'}[typ]
    folder = {'image': 'music-img', 'audio': 'music-mp3', 'lyrics': 'music-text'}[typ]
    return f"{SITE}{folder}/{quote(str(track['ID']), safe='')}%20({track['Img']}){suffix}"


def story_link(track):
    custom = str(track.get('Link') or '').strip()
    if custom:
        from urllib.parse import urljoin
        return urljoin(WWW, custom)
    match = re.match(r'^(\d{8}-\d{2})', str(track['ID']))
    return f'{WWW}Post.html?id=P{match[1]}' if match else ''


def replace_one(pattern, replacement, document):
    updated, count = re.subn(pattern, lambda _: replacement, document, count=1)
    if count != 1:
        raise RuntimeError('Cannot update HTML template: ' + pattern)
    return updated


def set_content(document, element_id, content, attr='content'):
    # The source template uses the same "id" tags as the dynamic JS SEO updater.
    rex = rf'(<(?:meta|link) id="{re.escape(element_id)}"[^>]*\b{attr}=")[^"]*(")'
    safe = html.escape(str(content), quote=True)
    match = re.search(rex, document)
    if not match:
        raise RuntimeError(f'Missing template element #{element_id}.{attr}')
    start, end = match.span()
    return document[:start] + match.group(1) + safe + match.group(2) + document[end:]


def build_page(template, track):
    name = str(track.get('TITLE') or 'Untitled')
    story = str(track.get('STORY') or 'YURI NO1')
    full_title = f'{name} \\ {TITLE_SUFFIX}'
    description = f'{name} — original YURI NO1 AI music inspired by {story}, connecting Girls Love novels, characters, and sound.'
    url = canonical(track)
    cover = media(track, 'image')
    mp3 = media(track, 'audio')
    schema = {
        '@context': 'https://schema.org',
        '@type': 'MusicRecording',
        'name': name,
        'url': url,
        'image': cover,
        'contentUrl': mp3,
        'description': description,
        'byArtist': {'@type': 'Organization', 'name': 'YURI NO1', 'url': WWW},
    }
    if story:
        link = story_link(track)
        schema['isBasedOn'] = ({'@type':'CreativeWork','name':story,'url':link} if link
                               else {'@type':'CreativeWork','name':story})
    document = replace_one(r'<title>[^<]*</title>', f'<title>{html.escape(full_title)}</title>', template)
    for id_,value,attr in (
        ('meta-description',description,'content'),('canonical',url,'href'),
        ('og-title',full_title,'content'),('og-description',description,'content'),
        ('og-url',url,'content'),('og-image',cover,'content'),
        ('twitter-title',full_title,'content'),('twitter-description',description,'content'),
        ('twitter-image',cover,'content'),
    ):
        document=set_content(document,id_,value,attr)
    json_ld=json.dumps(schema,ensure_ascii=False,indent=2).replace('</','<\\/')
    document=replace_one(r'<script id="structured-data" type="application/ld\+json">[\s\S]*?</script>',
        '<script id="structured-data" type="application/ld+json">\n  '+json_ld+'\n  </script>',document)
    return document.replace('<!doctype html>', '<!doctype html>\n'+GENERATED_MARKER, 1)


def clean_uppercase_lyric_duplicates(check):
    """Never delete unique lyric content just because it was accidentally capitalized."""
    directory=ROOT/'music-text'
    for path in directory.glob('*.txt'):
        if path.name == path.name.lower():
            continue
        corrected=path.with_name(path.name.lower())
        if not corrected.is_file() or path.read_bytes()!=corrected.read_bytes():
            raise ValueError(f'Uppercase lyric filename contains unique/different data; handle manually: {path.name}')
        if check:
            raise ValueError(f'Uppercase duplicate lyric filename still present: {path.name}')
        path.unlink()
        print('Removed duplicate uppercase lyric:',path.name)


def build(check=False):
    tracklog=json.loads((ROOT/'w-music/w-tracklog.json').read_text(encoding='utf-8'))
    tracks=tracklog['tracks'] if isinstance(tracklog,dict) else tracklog
    if not isinstance(tracks,list) or not tracks:
        raise ValueError('Missing tracks list')
    clean_uppercase_lyric_duplicates(check)
    # Previous patch shipped an uppercase-named note. Remove only if the new
    # lowercase note has exactly the same bytes, avoiding unrelated file loss.
    old_note = ROOT/'UPDATE-20261007.txt'
    new_note = ROOT/'update-20261007.txt'
    if old_note.exists():
        if check or not new_note.exists() or old_note.read_bytes()!=new_note.read_bytes():
            raise ValueError('Legacy uppercase UPDATE-20261007.txt still exists (contents differ)')
        old_note.unlink()
        print('Removed obsolete UPDATE-20261007.txt')
    template=(ROOT/'index.html').read_text(encoding='utf-8')
    desired={}
    url_set=set()
    for t in tracks:
        url=canonical(t)
        if url in url_set:
            raise ValueError(f'Duplicate URL: {url} (check url-title)')
        url_set.add(url)
        if relative_dir(t).as_posix() != relative_dir(t).as_posix().lower():
            raise ValueError('Uppercase path: '+url)
        desired[relative_dir(t)/'index.html']=build_page(template,t)
        lyric=(ROOT/'music-text'/f"{t['ID']} ({t['Img']}).txt")
        if not lyric.is_file():
            raise ValueError('Missing original lyric: '+str(lyric))
    existing=set()
    mdir=ROOT/'m'
    if mdir.exists():
        for path in mdir.glob('*/*/index.html'):
            old=path.read_text(encoding='utf-8')
            if 'id="structured-data"' not in old or 'class="music-app"' not in old:
                raise ValueError('Refusing to replace unknown page: '+str(path))
            existing.add(path.relative_to(ROOT))
    stale=existing-desired.keys()
    if check:
        for path,content in desired.items():
            if not (ROOT/path).is_file() or (ROOT/path).read_text(encoding='utf-8')!=content:
                raise ValueError('Generated track page out of date: '+str(path))
        if stale:
            raise ValueError('Stale track URL directories: '+', '.join(map(str,sorted(stale))))
    else:
        for path in stale:
            target=ROOT/path
            target.unlink()
            # Only remove empty generated slug and ID folders.
            for parent in (target.parent,target.parent.parent):
                if parent.is_dir() and not any(parent.iterdir()):
                    parent.rmdir()
        for path,content in desired.items():
            dest=ROOT/path
            dest.parent.mkdir(parents=True,exist_ok=True)
            if not dest.exists() or dest.read_text(encoding='utf-8')!=content:
                dest.write_text(content,encoding='utf-8')
    sitemap=('<?xml version="1.0" encoding="UTF-8"?>\n'
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
             f'  <url><loc>{SITE}</loc></url>\n'
             +''.join(f'  <url><loc>{html.escape(canonical(t))}</loc></url>\n' for t in tracks)
             +'</urlset>\n')
    target=ROOT/'sitemap.xml'
    if check:
        if target.read_text(encoding='utf-8')!=sitemap:
            raise ValueError('Outdated sitemap.xml')
    else:
        target.write_text(sitemap,encoding='utf-8')
    for path in ROOT.rglob('*'):
        if '.github' in path.parts or '.git' in path.parts or not path.is_file():
            continue
        rel=path.relative_to(ROOT)
        if rel.as_posix() != rel.as_posix().lower():
            raise ValueError('Uppercase filename not permitted: '+str(rel))
    print(f'{"PASS" if check else "Built"}: {len(tracks)} pages; {len(stale)} obsolete URL(s); sitemap; lowercase filenames; lyrics verified.')


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true',help='Only verify, do not modify')
    args=parser.parse_args()
    try: build(args.check)
    except (ValueError, RuntimeError) as e:
        print('Music build error:',e,file=sys.stderr)
        sys.exit(1)
